### ISSUE TITLE
Why injected style width to all the child elements?

### ISSUE THREAD

**Issue by rohmanhm** [andela-foladeji/react-slideshow#25]
Why do you have `style='width: 1585px'` to all the child elements. It just doesn't make sense. It's broke my design.

![image](https://user-images.githubusercontent.com/7524911/49787370-16b9eb80-fd59-11e8-8cc5-21c4e084b938.png)

**Comment by andela-foladeji** [comment]
So sorry about that. I will look into it asap and get back to you. I’m sorry for the inconvenience.

**Comment by andela-foladeji** [comment]
Hi @rohmanhm I've fixed the bug here https://github.com/andela-foladeji/react-slideshow/pull/26, it was an oversight. Thanks for pointing it out. 👍 🏅
