### ISSUE TITLE
Warning: Failed prop type: Slideshow: prop type `transitionDuration` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.

### ISSUE THREAD

**Issue by varvarasd** [andela-foladeji/react-slideshow#5]
Hi,

FYI I'm getting this error
`Warning: Failed prop type: Slideshow: prop type 'transitionDuration' is invalid; it must be a function, usually from the 'prop-types' package, but received 'undefined'.`

I tried deleting the `transitionDuration` and `duration` attr and still get this error

**Comment by andela-foladeji** [comment]
I'll take a look at it and get back to you

**Comment by andela-foladeji** [comment]
This issue has been fixed now @varvarasd. Thanks for pointing it out
