### ISSUE TITLE
Import error: react-slideshow-image module import error

### ISSUE THREAD

**Issue by AnoushS** [andela-foladeji/react-slideshow#6]
When I'm trying import this module, gives this error

ERROR in ./node_modules/react-slideshow-image/lib/components/slideshow/fade.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .fade-wrapper {
|   width: 100%;
|   overflow: hidden; }
 @ ./node_modules/react-slideshow-image/lib/components/slideshow/fade.js 12:0-20
 @ ./node_modules/react-slideshow-image/lib/index.js
 @ ./src/app/routing/components/CategoriesList/ProductDetails.js
 @ ./src/app/routing/components/CategoriesList/CategoriesProductsListView.js
 @ ./src/app/components/MainContent.js
 @ ./src/app/routing/MainWrapper.js
 @ ./src/app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/app/index.js

ERROR in ./node_modules/react-slideshow-image/lib/components/slideshow/slide.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .slideshow-wrapper.slide {
|   width: 100%;
|   overflow: hidden; }
 @ ./node_modules/react-slideshow-image/lib/components/slideshow/slide.js 12:0-21
 @ ./node_modules/react-slideshow-image/lib/index.js
 @ ./src/app/routing/components/CategoriesList/ProductDetails.js
 @ ./src/app/routing/components/CategoriesList/CategoriesProductsListView.js
 @ ./src/app/components/MainContent.js
 @ ./src/app/routing/MainWrapper.js
 @ ./src/app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/app/index.js

ERROR in ./node_modules/react-slideshow-image/lib/components/slideshow/zoom.css
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .zoom-wrapper {
|   width: 100%;
|   overflow: hidden; }
 @ ./node_modules/react-slideshow-image/lib/components/slideshow/zoom.js 12:0-20
 @ ./node_modules/react-slideshow-image/lib/index.js
 @ ./src/app/routing/components/CategoriesList/ProductDetails.js
 @ ./src/app/routing/components/CategoriesList/CategoriesProductsListView.js
 @ ./src/app/components/MainContent.js
 @ ./src/app/routing/MainWrapper.js
 @ ./src/app/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/app/index.js

**Comment by andela-foladeji** [comment]
@AnoushS I'll check this and get back to you, I must have missed something

**Comment by andela-foladeji** [comment]
@AnoushS I've fixed the issue, you may need to uninstall and reinstall the package. And follow the instruction [here](https://github.com/andela-foladeji/react-slideshow#webpack-configuration). The error was that the `css-loader` and `style-loader` modules were missing. Let me know if you experience another bug

**Comment by banada** [comment]
I am encountering the same issue, even with css-loader and style-loader installed and added to my webpack config:

```
{
    test: /\.css$/i,
    use: ['css-loader', 'style-loader']
}
```

**Comment by femioladeji** [comment]
@banada Probably something is missing in your webpack config. You can check this sandbox to see what I did https://codesandbox.io/s/bold-fermat-eqvlq

**Comment by bryantobing12** [comment]
I'm using create react app and do not have webpack.config.js . how to solved this?

**Comment by femioladeji** [comment]
@bryantobing12 you shouldn't be having any error if you're using create-react-app. Can you check [this implementation] (https://codesandbox.io/s/admiring-wave-17e0j)
